"""Add user_type and consents

Revision ID: aaf9ee727619
Revises: ae970c14e138
Create Date: 2026-09-01 23:46:40.628689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf9ee727619'
down_revision = 'ae970c14e138'
branch_labels = None
depends_on = None

# Frozen copy of services.consent_service.PURPOSE_CATEGORIES at the time of this
# migration. Inlined deliberately: a migration must keep backfilling the same
# rows even after the application's map evolves.
PURPOSE_CATEGORIES = {
    "financial_health_analysis": (
        "profile", "income", "expenses", "accounts", "assets", "goals", "liabilities",
    ),
    "budgeting": ("profile", "expenses", "transactions"),
    "purchase_advisor": ("profile", "income", "expenses", "accounts", "liabilities"),
    "alternative_recommendations": (
        "profile", "income", "expenses", "accounts", "assets", "goals",
    ),
    "ai_assistant": ("profile", "income", "expenses", "goals", "transactions"),
    "credit_readiness": ("profile", "income", "expenses", "accounts", "liabilities"),
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data_category', sa.String(length=30), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'data_category', 'purpose', name='uq_consent_user_cat_purpose')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_consents_user_purpose', ['user_id', 'purpose'], unique=False)

    # server_default lets this run against a table that already has rows; the
    # ORM-side default keeps new inserts explicit.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'user_type', sa.String(length=20),
            nullable=False, server_default='general',
        ))

    _backfill_consents()
    # ### end Alembic commands ###


def _backfill_consents():
    """Grant the default consent matrix to every pre-existing user.

    Without this, accounts created before the consent engine existed would
    silently lose access to the health score, analyzer and coach.
    """
    pairs = [
        (category, purpose)
        for purpose, categories in PURPOSE_CATEGORIES.items()
        for category in categories
    ]
    values = ", ".join(f"('{c}', '{p}')" for c, p in pairs)
    op.execute(f"""
        INSERT INTO consents (
            id, user_id, data_category, purpose, granted,
            granted_at, version, source, created_at, updated_at
        )
        SELECT
            gen_random_uuid(), u.id, m.data_category, m.purpose, true,
            NOW(), 1, 'default_seed', NOW(), NOW()
        FROM users u
        CROSS JOIN (VALUES {values}) AS m(data_category, purpose)
        ON CONFLICT ON CONSTRAINT uq_consent_user_cat_purpose DO NOTHING
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index('ix_consents_user_purpose')
        batch_op.drop_index(batch_op.f('ix_consents_user_id'))

    op.drop_table('consents')
    # ### end Alembic commands ###
